name: Deployment to EC2 instance of Amazon

on:
  push:
    branches:
      - master

job:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with: 
          host: ${{ secrets.SSH_IP_EC2 }}
          username: ec2-user
          key: ${{ secrets.SSH_KEY_EC2 }}
          script: |
            cd /home/ec2-user/ExampleWebApp
            git pull
            npm install
            npm run build
            sudo mv ./dist/* /var/www/html
            

